binary: "crossfid"
home_dir: "./chain_data"
keyring_backend: "file"
seed:
  name: "seed"
  addr: "127.0.0.1:26656"
  client:
    keyring-backend: file
    broadcast-mode: block
  app:
    json-rpc:
      address: "0.0.0.0:8545"
      ws-address: "0.0.0.0:8546"
      api: "eth,txpool,net,debug,web3"
      enable: true
      enable-indexer: true
    api:
      enable: true
    pruning: "nothing"
    state-sync:
      snapshot-interval: 10000
      snapshot-keep-recent: 2
  config:
    p2p:
      allow_duplicate_ip: true
      laddr: "tcp://0.0.0.0:26656"
      seeds: ""
    rpc:
      pprof_laddr: ""
      laddr: "tcp://0.0.0.0:26657"
genesis:
  chain_id: "crossfi-evm-testnet-1"
  genesis_time: "2023-10-15T00:00:00.000000Z"
  app_state:
    evm:
      params:
        evm_denom:
          mpx
    crisis:
      constant_fee:
        denom: mpx
    gov:
      deposit_params:
        min_deposit:
          - amount: "1000000000000000000"
            denom: mpx
      voting_params:
        voting_period:
          600s
    staking:
      params:
        bond_denom: mpx
        max_validators: 64
        unbonding_time: 6000s
    treasury:
      params:
        owner: mx1fv9cgmsgvs4r4f346axfd76twmjd7mqllwndy5
accounts:
  - name: myacc
    coins:
      - 100000000000000000000000000000mpx
      - 100000000000000000000000000000xfi
validators:
  - name: validator1
    bonded: 1000000000000000000000000mpx
    client:
      keyring-backend: file
      broadcast-mode: block
    config:
      p2p:
        allow_duplicate_ip: true
        laddr: "tcp://0.0.0.0:36650"
      rpc:
        laddr: ""
        pprof_laddr: ""
      storage:
        discard_abci_responses: true
    app:
      pruning: everything
      state-sync:
        snapshot-interval: 0
        snapshot-keep-recent: 0
      min-retain-blocks: 10
      grpc:
        enable: false
      grpc-web:
        enable: false
      json-rpc:
        enable: false
      rosetta:
        enable: false
  - name: validator2
    bonded: 1000000000000000000000000mpx
    client:
      keyring-backend: file
      broadcast-mode: block
    config:
      p2p:
        allow_duplicate_ip: true
        laddr: "tcp://0.0.0.0:36651"
      rpc:
        laddr: ""
        pprof_laddr: ""
      storage:
        discard_abci_responses: true
    app:
      pruning: everything
      state-sync:
        snapshot-interval: 0
        snapshot-keep-recent: 0
      min-retain-blocks: 10
      grpc:
        enable: false
      grpc-web:
        enable: false
      json-rpc:
        enable: false
      rosetta:
        enable: false
  - name: validator3
    bonded: 1000000000000000000000000mpx
    client:
      keyring-backend: file
      broadcast-mode: block
    config:
      p2p:
        allow_duplicate_ip: true
        laddr: "tcp://0.0.0.0:36652"
      rpc:
        laddr: ""
        pprof_laddr: ""
      storage:
        discard_abci_responses: true
    app:
      pruning: everything
      state-sync:
        snapshot-interval: 0
        snapshot-keep-recent: 0
      min-retain-blocks: 10
      grpc:
        enable: false
      grpc-web:
        enable: false
      json-rpc:
        enable: false
      rosetta:
        enable: false
  - name: validator4
    bonded: 1000000000000000000000000mpx
    client:
      keyring-backend: file
      broadcast-mode: block
    config:
      p2p:
        allow_duplicate_ip: true
        laddr: "tcp://0.0.0.0:36653"
      rpc:
        laddr: ""
        pprof_laddr: ""
      storage:
        discard_abci_responses: true
    app:
      pruning: everything
      state-sync:
        snapshot-interval: 0
        snapshot-keep-recent: 0
      min-retain-blocks: 10
      grpc:
        enable: false
      grpc-web:
        enable: false
      json-rpc:
        enable: false
      rosetta:
        enable: false